backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
display_url: "https://www.adt-theatre.sk"
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "oznamy" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Novinky" # Used in the UI, ie.: "New Post"
    label_singular: "Novinka"
    folder: "site/content/oznamy" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Klub",
          name: "klub",
          widget: "relation",
          collection: "kluby",
          searchFields: ["title"],
          displayFields: ["title"],
          valueField: "title",
          required: false,
        }
      - { label: "Intro", name: "intro", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "clanky" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Články" # Used in the UI, ie.: "New Post"
    label_singular: "Článok"
    folder: "site/content/clanky" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Intro", name: "intro", widget: "text" }
      - { label: "Featured Image", name: "featured_img", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "kluby" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Kluby" # Used in the UI, ie.: "New Post"
    label_singular: "Klub"
    folder: "site/content/kluby" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Stránky"
    label_singular: "Stránka"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Perex, name: perex, widget: markdown }
          - { label: Footer, name: footer, widget: markdown }
      - file: "site/content/o-akademii.md"
        label: "O akadémii"
        name: "o-akademii"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "site/content/kluby.md"
        label: "Kluby"
        name: "kluby"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "site/content/clenovia.md"
        label: "Členovia"
        name: "clenovia"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "site/content/dokumenty.md"
        label: "Dokumenty"
        name: "dokumenty"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "site/content/stanovy.md"
        label: "Stanovy Akadémie"
        name: "stanovy"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "site/content/statut-ceny.md"
        label: "Štatút Ceny"
        name: "statut-ceny"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "site/content/eticky-kodex.md"
        label: "Etický kódex"
        name: "eticky-kodex"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "site/content/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
